name: 'Pull Request Checks'
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]
permissions:
  pull-requests: write
  checks: write
  contents: read
jobs:
  pr-checks:
    uses: ikigai-digital/github-workflow-templates/.github/workflows/util-pr-checks.yml@main
